### ISSUE TITLE
make -e PROJECT={PROJECT}生成的dependencies字段和开源原有的dependencies字段没有合并

### ISSUE THREAD

**Issue by usernameisnull** [DaoCloud/dce-charts-repackage#510]
argo-cd的Charts.yaml里原本就有dependencies字段，使用make -e PROJECT=argo-cd在Charts.yaml里会有2个dependencies字段
```yaml
annotations:
  artifacthub.io/changes: |
    - "[Removed]: Legacy API versions for Ingresses"
apiVersion: v2
appVersion: v2.5.5
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.22.4
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool
  for Kubernetes.
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- gitops
kubeVersion: '>=1.22.0-0'
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-cd
sources:
- https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- https://github.com/argoproj/argo-cd
version: 5.16.13
dependencies:
  - name: argo-cd
    version: "5.16.13"
    repository: "https://argoproj.github.io/argo-helm"
```
